import turtle
from test.test_socket import BasicBluetoothTest
from turtle import done
aScreen=turtle.Screen()
t_size = 100
blueT=turtle.Turtle()
blueT.color('green')
blueT.width(10)
blueT.showturtle()
blueT.left(90)
blueT.forward(t_size)
blueT.right(180)
blueT.forward(t_size/2)
blueT.left(90)
blueT.forward(t_size/2)
blueT.right(90)
blueT.forward(t_size/2)
blueT.right(180)
blueT.forward(t_size)
blueT.right(90)
blueT.up()
blueT.forward(t_size/2)
blueT.down()
blueT.forward(t_size/4)
blueT.left(180)
blueT.forward(t_size/8)
blueT.left(90)
blueT.forward(t_size)
blueT.right(90)
blueT.forward(t_size/8)
blueT.left(180)
blueT.forward(t_size/4)
done()

